### ISSUE TITLE
jsuite CSS rgb function change to rgba

### ISSUE THREAD

**Issue by jainpradeep** [paulhodel/jsuites#20]
4 argument passed into rgb function instead of 3. Typescript expects exact number of arguments to be passed(works in pure JS). Project build failing due to this. Request to please change the function to rgba.  

ERROR in ./node_modules/jsuites/dist/jsuites.css (./node_modules/css-loader/dist/cjs.js!./node_modules/sass-loader/dist/cjs.js!./node_modules/jsuites/dist/jsuites.css)
Module build failed:
        background: rgb(255,255,255,0.95);

**Comment by paulhodel** [comment]
This has been fixed and It will be deployed soon. Thanks for spotting that.

**Comment by jainpradeep** [comment]
Sir,

The issue still persists.
![image](https://user-images.githubusercontent.com/13506321/75516183-d14b1200-5a21-11ea-8a5c-91390550defb.png)
