### ISSUE TITLE
rgba called with wrong number of arguments

### ISSUE THREAD

**Issue by mercurio** [paulhodel/jsuites#22]
I'm including jExcel in a Svelte app and getting an error from Sass about rgba being called with the wrong number of arguments. It looks like the problem is at line 2889 of dist/jsuites.css, it should either use rgb() or add the 4th argument to the rgba() call. Also, line 2888 appears to have a typo, 'backgroun-color' instead of 'background-color'.

**Comment by paulhodel** [comment]
It has been fixed.

**Comment by syabro** [comment]
https://github.com/paulhodel/jsuites/blob/master/dist/jsuites.css#L2946
Nope, not fixed

**Comment by paulhodel** [comment]
This has been fixed.
